Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,5 +22,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: |
-          echo ${{ success() }}
-          echo ${{ failure() }}
+          if [[ ${{ needs.job-two.result != 'success' || needs.job-three.result != 'success' ]]; then
+            echo "Tests have failed"
+            exit 1
+          fi
+
+          echo "Tests have passed"
